//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TraderaWebServiceClient.TraderaSearch {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchServiceSoap", Namespace="http://api.tradera.com")]
    public partial class SearchService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthenticationHeader authenticationHeaderValueField;
        
        private ConfigurationHeader configurationHeaderValueField;
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchAdvancedOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchCategoryCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByFixedCriteriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByZipCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SearchService() {
            this.Url = global::TraderaWebServiceClient.Properties.Settings.Default.TraderaWebServiceClient_TraderaSearch_SearchService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationHeader AuthenticationHeaderValue {
            get {
                return this.authenticationHeaderValueField;
            }
            set {
                this.authenticationHeaderValueField = value;
            }
        }
        
        public ConfigurationHeader ConfigurationHeaderValue {
            get {
                return this.configurationHeaderValueField;
            }
            set {
                this.configurationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        public event SearchAdvancedCompletedEventHandler SearchAdvancedCompleted;
        
        /// <remarks/>
        public event SearchCategoryCountCompletedEventHandler SearchCategoryCountCompleted;
        
        /// <remarks/>
        public event SearchByFixedCriteriaCompletedEventHandler SearchByFixedCriteriaCompleted;
        
        /// <remarks/>
        public event SearchByZipCodeCompletedEventHandler SearchByZipCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ConfigurationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.tradera.com/Search", RequestNamespace="http://api.tradera.com", ResponseNamespace="http://api.tradera.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult Search(string query, int categoryId, int pageNumber, string orderBy) {
            object[] results = this.Invoke("Search", new object[] {
                        query,
                        categoryId,
                        pageNumber,
                        orderBy});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(string query, int categoryId, int pageNumber, string orderBy) {
            this.SearchAsync(query, categoryId, pageNumber, orderBy, null);
        }
        
        /// <remarks/>
        public void SearchAsync(string query, int categoryId, int pageNumber, string orderBy, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        query,
                        categoryId,
                        pageNumber,
                        orderBy}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ConfigurationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.tradera.com/SearchAdvanced", RequestNamespace="http://api.tradera.com", ResponseNamespace="http://api.tradera.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult SearchAdvanced(SearchAdvancedRequest request) {
            object[] results = this.Invoke("SearchAdvanced", new object[] {
                        request});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAdvancedAsync(SearchAdvancedRequest request) {
            this.SearchAdvancedAsync(request, null);
        }
        
        /// <remarks/>
        public void SearchAdvancedAsync(SearchAdvancedRequest request, object userState) {
            if ((this.SearchAdvancedOperationCompleted == null)) {
                this.SearchAdvancedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchAdvancedOperationCompleted);
            }
            this.InvokeAsync("SearchAdvanced", new object[] {
                        request}, this.SearchAdvancedOperationCompleted, userState);
        }
        
        private void OnSearchAdvancedOperationCompleted(object arg) {
            if ((this.SearchAdvancedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchAdvancedCompleted(this, new SearchAdvancedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ConfigurationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.tradera.com/SearchCategoryCount", RequestNamespace="http://api.tradera.com", ResponseNamespace="http://api.tradera.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CategoryCountResult SearchCategoryCount(CategoryCountRequest request) {
            object[] results = this.Invoke("SearchCategoryCount", new object[] {
                        request});
            return ((CategoryCountResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchCategoryCountAsync(CategoryCountRequest request) {
            this.SearchCategoryCountAsync(request, null);
        }
        
        /// <remarks/>
        public void SearchCategoryCountAsync(CategoryCountRequest request, object userState) {
            if ((this.SearchCategoryCountOperationCompleted == null)) {
                this.SearchCategoryCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchCategoryCountOperationCompleted);
            }
            this.InvokeAsync("SearchCategoryCount", new object[] {
                        request}, this.SearchCategoryCountOperationCompleted, userState);
        }
        
        private void OnSearchCategoryCountOperationCompleted(object arg) {
            if ((this.SearchCategoryCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCategoryCountCompleted(this, new SearchCategoryCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ConfigurationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.tradera.com/SearchByFixedCriteria", RequestNamespace="http://api.tradera.com", ResponseNamespace="http://api.tradera.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult SearchByFixedCriteria(SearchByFixedCriteriaRequest request) {
            object[] results = this.Invoke("SearchByFixedCriteria", new object[] {
                        request});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByFixedCriteriaAsync(SearchByFixedCriteriaRequest request) {
            this.SearchByFixedCriteriaAsync(request, null);
        }
        
        /// <remarks/>
        public void SearchByFixedCriteriaAsync(SearchByFixedCriteriaRequest request, object userState) {
            if ((this.SearchByFixedCriteriaOperationCompleted == null)) {
                this.SearchByFixedCriteriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByFixedCriteriaOperationCompleted);
            }
            this.InvokeAsync("SearchByFixedCriteria", new object[] {
                        request}, this.SearchByFixedCriteriaOperationCompleted, userState);
        }
        
        private void OnSearchByFixedCriteriaOperationCompleted(object arg) {
            if ((this.SearchByFixedCriteriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByFixedCriteriaCompleted(this, new SearchByFixedCriteriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ConfigurationHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://api.tradera.com/SearchByZipCode", RequestNamespace="http://api.tradera.com", ResponseNamespace="http://api.tradera.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchResult SearchByZipCode(SearchByZipCodeRequest request) {
            object[] results = this.Invoke("SearchByZipCode", new object[] {
                        request});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByZipCodeAsync(SearchByZipCodeRequest request) {
            this.SearchByZipCodeAsync(request, null);
        }
        
        /// <remarks/>
        public void SearchByZipCodeAsync(SearchByZipCodeRequest request, object userState) {
            if ((this.SearchByZipCodeOperationCompleted == null)) {
                this.SearchByZipCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByZipCodeOperationCompleted);
            }
            this.InvokeAsync("SearchByZipCode", new object[] {
                        request}, this.SearchByZipCodeOperationCompleted, userState);
        }
        
        private void OnSearchByZipCodeOperationCompleted(object arg) {
            if ((this.SearchByZipCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByZipCodeCompleted(this, new SearchByZipCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.tradera.com", IsNullable=false)]
    public partial class ConfigurationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private int sandboxField;
        
        private int maxResultAgeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public int Sandbox {
            get {
                return this.sandboxField;
            }
            set {
                this.sandboxField = value;
            }
        }
        
        /// <remarks/>
        public int MaxResultAge {
            get {
                return this.maxResultAgeField;
            }
            set {
                this.maxResultAgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchByZipCodeRequest {
        
        private string zipCodeField;
        
        private int pageNumberField;
        
        private string orderByField;
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchByFixedCriteriaRequest {
        
        private string nameField;
        
        private int pageNumberField;
        
        private string itemTypeField;
        
        private string orderByField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchCategory {
        
        private int idField;
        
        private string nameField;
        
        private int noOfItemsInCategoryField;
        
        private int noOfItemsInCategoryIncludingChildrenField;
        
        private SearchCategory[] childCategoriesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfItemsInCategory {
            get {
                return this.noOfItemsInCategoryField;
            }
            set {
                this.noOfItemsInCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int NoOfItemsInCategoryIncludingChildren {
            get {
                return this.noOfItemsInCategoryIncludingChildrenField;
            }
            set {
                this.noOfItemsInCategoryIncludingChildrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChildCategories")]
        public SearchCategory[] ChildCategories {
            get {
                return this.childCategoriesField;
            }
            set {
                this.childCategoriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class CategoryCountResult {
        
        private SearchCategory[] categoriesField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categories")]
        public SearchCategory[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors")]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class CategoryCountRequest {
        
        private int categoryIdField;
        
        private string aliasField;
        
        private int countyIdField;
        
        private bool searchInDescriptionField;
        
        private string itemConditionField;
        
        private string zipCodeField;
        
        private string searchWordsField;
        
        private int pageNumberField;
        
        private bool onlyItemsWithThumbnailField;
        
        private bool onlyAuctionsWithBuyNowField;
        
        private string modeField;
        
        private System.Nullable<int> priceMinimumField;
        
        private System.Nullable<int> priceMaximumField;
        
        private System.Nullable<int> bidsMinimumField;
        
        private System.Nullable<int> bidsMaximumField;
        
        private string itemStatusField;
        
        private string itemTypeField;
        
        private string sellerTypeField;
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public int CountyId {
            get {
                return this.countyIdField;
            }
            set {
                this.countyIdField = value;
            }
        }
        
        /// <remarks/>
        public bool SearchInDescription {
            get {
                return this.searchInDescriptionField;
            }
            set {
                this.searchInDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCondition {
            get {
                return this.itemConditionField;
            }
            set {
                this.itemConditionField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SearchWords {
            get {
                return this.searchWordsField;
            }
            set {
                this.searchWordsField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyItemsWithThumbnail {
            get {
                return this.onlyItemsWithThumbnailField;
            }
            set {
                this.onlyItemsWithThumbnailField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyAuctionsWithBuyNow {
            get {
                return this.onlyAuctionsWithBuyNowField;
            }
            set {
                this.onlyAuctionsWithBuyNowField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PriceMinimum {
            get {
                return this.priceMinimumField;
            }
            set {
                this.priceMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PriceMaximum {
            get {
                return this.priceMaximumField;
            }
            set {
                this.priceMaximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BidsMinimum {
            get {
                return this.bidsMinimumField;
            }
            set {
                this.bidsMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BidsMaximum {
            get {
                return this.bidsMaximumField;
            }
            set {
                this.bidsMaximumField = value;
            }
        }
        
        /// <remarks/>
        public string ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SellerType {
            get {
                return this.sellerTypeField;
            }
            set {
                this.sellerTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchAdvancedRequest {
        
        private string searchWordsField;
        
        private int categoryIdField;
        
        private bool searchInDescriptionField;
        
        private string modeField;
        
        private System.Nullable<int> priceMinimumField;
        
        private System.Nullable<int> priceMaximumField;
        
        private System.Nullable<int> bidsMinimumField;
        
        private System.Nullable<int> bidsMaximumField;
        
        private string zipCodeField;
        
        private int countyIdField;
        
        private string aliasField;
        
        private string orderByField;
        
        private string itemStatusField;
        
        private string itemTypeField;
        
        private bool onlyAuctionsWithBuyNowField;
        
        private bool onlyItemsWithThumbnailField;
        
        private int itemsPerPageField;
        
        private int pageNumberField;
        
        private string itemConditionField;
        
        private string sellerTypeField;
        
        private string[] brandsField;
        
        private int[] campaignCodeIdsField;
        
        /// <remarks/>
        public string SearchWords {
            get {
                return this.searchWordsField;
            }
            set {
                this.searchWordsField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public bool SearchInDescription {
            get {
                return this.searchInDescriptionField;
            }
            set {
                this.searchInDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PriceMinimum {
            get {
                return this.priceMinimumField;
            }
            set {
                this.priceMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PriceMaximum {
            get {
                return this.priceMaximumField;
            }
            set {
                this.priceMaximumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BidsMinimum {
            get {
                return this.bidsMinimumField;
            }
            set {
                this.bidsMinimumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BidsMaximum {
            get {
                return this.bidsMaximumField;
            }
            set {
                this.bidsMaximumField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        public int CountyId {
            get {
                return this.countyIdField;
            }
            set {
                this.countyIdField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public string OrderBy {
            get {
                return this.orderByField;
            }
            set {
                this.orderByField = value;
            }
        }
        
        /// <remarks/>
        public string ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyAuctionsWithBuyNow {
            get {
                return this.onlyAuctionsWithBuyNowField;
            }
            set {
                this.onlyAuctionsWithBuyNowField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyItemsWithThumbnail {
            get {
                return this.onlyItemsWithThumbnailField;
            }
            set {
                this.onlyItemsWithThumbnailField = value;
            }
        }
        
        /// <remarks/>
        public int ItemsPerPage {
            get {
                return this.itemsPerPageField;
            }
            set {
                this.itemsPerPageField = value;
            }
        }
        
        /// <remarks/>
        public int PageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCondition {
            get {
                return this.itemConditionField;
            }
            set {
                this.itemConditionField = value;
            }
        }
        
        /// <remarks/>
        public string SellerType {
            get {
                return this.sellerTypeField;
            }
            set {
                this.sellerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] Brands {
            get {
                return this.brandsField;
            }
            set {
                this.brandsField = value;
            }
        }
        
        /// <remarks/>
        public int[] CampaignCodeIds {
            get {
                return this.campaignCodeIdsField;
            }
            set {
                this.campaignCodeIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchItem {
        
        private int idField;
        
        private string shortDescriptionField;
        
        private System.Nullable<int> buyItNowPriceField;
        
        private int sellerIdField;
        
        private string sellerAliasField;
        
        private System.Nullable<int> maxBidField;
        
        private string thumbnailLinkField;
        
        private double sellerDsrAverageField;
        
        private System.DateTime endDateField;
        
        private System.Nullable<int> nextBidField;
        
        private bool hasBidsField;
        
        private bool isEndedField;
        
        private string itemTypeField;
        
        private int categoryIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ShortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BuyItNowPrice {
            get {
                return this.buyItNowPriceField;
            }
            set {
                this.buyItNowPriceField = value;
            }
        }
        
        /// <remarks/>
        public int SellerId {
            get {
                return this.sellerIdField;
            }
            set {
                this.sellerIdField = value;
            }
        }
        
        /// <remarks/>
        public string SellerAlias {
            get {
                return this.sellerAliasField;
            }
            set {
                this.sellerAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaxBid {
            get {
                return this.maxBidField;
            }
            set {
                this.maxBidField = value;
            }
        }
        
        /// <remarks/>
        public string ThumbnailLink {
            get {
                return this.thumbnailLinkField;
            }
            set {
                this.thumbnailLinkField = value;
            }
        }
        
        /// <remarks/>
        public double SellerDsrAverage {
            get {
                return this.sellerDsrAverageField;
            }
            set {
                this.sellerDsrAverageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NextBid {
            get {
                return this.nextBidField;
            }
            set {
                this.nextBidField = value;
            }
        }
        
        /// <remarks/>
        public bool HasBids {
            get {
                return this.hasBidsField;
            }
            set {
                this.hasBidsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsEnded {
            get {
                return this.isEndedField;
            }
            set {
                this.isEndedField = value;
            }
        }
        
        /// <remarks/>
        public string ItemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    public partial class SearchResult {
        
        private int totalNumberOfItemsField;
        
        private int totalNumberOfPagesField;
        
        private SearchItem[] itemsField;
        
        private Error[] errorsField;
        
        /// <remarks/>
        public int TotalNumberOfItems {
            get {
                return this.totalNumberOfItemsField;
            }
            set {
                this.totalNumberOfItemsField = value;
            }
        }
        
        /// <remarks/>
        public int TotalNumberOfPages {
            get {
                return this.totalNumberOfPagesField;
            }
            set {
                this.totalNumberOfPagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public SearchItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Errors")]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.tradera.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.tradera.com", IsNullable=false)]
    public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private int appIdField;
        
        private string appKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public int AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
            }
        }
        
        /// <remarks/>
        public string AppKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SearchAdvancedCompletedEventHandler(object sender, SearchAdvancedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchAdvancedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchAdvancedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SearchCategoryCountCompletedEventHandler(object sender, SearchCategoryCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCategoryCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCategoryCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CategoryCountResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CategoryCountResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SearchByFixedCriteriaCompletedEventHandler(object sender, SearchByFixedCriteriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByFixedCriteriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByFixedCriteriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SearchByZipCodeCompletedEventHandler(object sender, SearchByZipCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByZipCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByZipCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591